"""Add Meetings and StickyNotes

Revision ID: 41e0c046dd42
Revises: eddecb513b86
Create Date: 2026-07-23 22:21:39.098334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e0c046dd42'
down_revision: Union[str, None] = 'eddecb513b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('room_slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.String(length=30), nullable=True),
    sa.Column('ended_at', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_meetings_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings')),
    sa.UniqueConstraint('room_slug', name='uq_meeting_room_slug')
    )
    op.create_index(op.f('ix_meetings_deleted_at'), 'meetings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index('ix_meetings_project', 'meetings', ['project_id'], unique=False)
    op.create_table('sticky_notes',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sticky_notes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sticky_notes'))
    )
    op.create_index(op.f('ix_sticky_notes_deleted_at'), 'sticky_notes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sticky_notes_id'), 'sticky_notes', ['id'], unique=False)
    op.create_index('ix_sticky_notes_project', 'sticky_notes', ['project_id'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('external_email', sa.String(length=255), nullable=True),
    sa.Column('invited_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_meeting_attendees_invited_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_attendees_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meeting_attendees_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_attendees'))
    )
    op.create_index('ix_attendees_meeting', 'meeting_attendees', ['meeting_id'], unique=False)
    op.create_index('ix_attendees_user', 'meeting_attendees', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendees_user', table_name='meeting_attendees')
    op.drop_index('ix_attendees_meeting', table_name='meeting_attendees')
    op.drop_table('meeting_attendees')
    op.drop_index('ix_sticky_notes_project', table_name='sticky_notes')
    op.drop_index(op.f('ix_sticky_notes_id'), table_name='sticky_notes')
    op.drop_index(op.f('ix_sticky_notes_deleted_at'), table_name='sticky_notes')
    op.drop_table('sticky_notes')
    op.drop_index('ix_meetings_project', table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_deleted_at'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
