"""Add AuditMixin to StickyNote

Revision ID: 6f81283a566f
Revises: 41e0c046dd42
Create Date: 2026-07-23 23:44:42.109185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f81283a566f'
down_revision: Union[str, None] = '41e0c046dd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticky_notes', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('sticky_notes', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_sticky_notes_created_by_users'), 'sticky_notes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_sticky_notes_updated_by_users'), 'sticky_notes', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sticky_notes_updated_by_users'), 'sticky_notes', type_='foreignkey')
    op.drop_constraint(op.f('fk_sticky_notes_created_by_users'), 'sticky_notes', type_='foreignkey')
    op.drop_column('sticky_notes', 'updated_by')
    op.drop_column('sticky_notes', 'created_by')
    # ### end Alembic commands ###
