"""Add cover_image to projects

Revision ID: eddecb513b86
Revises: 44f3687e095f
Create Date: 2026-07-23 10:53:54.178946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddecb513b86'
down_revision: Union[str, None] = '44f3687e095f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_issue_assignee', 'issue_assignees', ['issue_id', 'user_id'])
    op.create_unique_constraint('uq_issue_label', 'issue_label_links', ['issue_id', 'label_id'])
    op.add_column('projects', sa.Column('cover_image', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'cover_image')
    op.drop_constraint('uq_issue_label', 'issue_label_links', type_='unique')
    op.drop_constraint('uq_issue_assignee', 'issue_assignees', type_='unique')
    # ### end Alembic commands ###
